### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by mhkeller** [dalejung/choir#1]
This looks like an interesting project but it's unclear how to get the demo up and running. Can you provide a walkthrough? When I try and run the files in the `bin/` folder on a file or directory I get the following error:

```
~/project/node_modules/choir/lib/magic/run_magic.js:11
var Script = process.binding('evals').NodeScript;
                     ^
Error: No such module: evals
```

**Comment by dalejung** [comment]
hey Michael, what version of node.js are you running?

**Comment by mhkeller** [comment]
0.12.0

**Comment by dalejung** [comment]
I misread your earlier comment. Does just typing `choir` work?

**Comment by mhkeller** [comment]
```
➜  brush git:(master) ✗ pwd
~/test/choir/demo/brush
➜  brush git:(master) ✗ ls
README.txt      brush.html      brush.js        brush_dom.js    choir_premod.js sp500.csv
➜  brush git:(master) ✗ %run brush.js
fg: job not found: run
➜  brush git:(master) ✗ choir
/usr/local/lib/node_modules/choir/lib/magic/run_magic.js:11
var Script = process.binding('evals').NodeScript;
                     ^
Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/choir/lib/magic/run_magic.js:11:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/choir/lib/choir_server.js:8:17)
    at Module._compile (module.js:460:26)
➜  brush git:(master) ✗ choir brush.js
/usr/local/lib/node_modules/choir/lib/magic/run_magic.js:11
var Script = process.binding('evals').NodeScript;
                     ^
Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/choir/lib/magic/run_magic.js:11:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/choir/lib/choir_server.js:8:17)
    at Module._compile (module.js:460:26)
➜  brush git:(master) ✗ choir brush.html
/usr/local/lib/node_modules/choir/lib/magic/run_magic.js:11
var Script = process.binding('evals').NodeScript;
                     ^
Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/choir/lib/magic/run_magic.js:11:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/choir/lib/choir_server.js:8:17)
    at Module._compile (module.js:460:26)
```
